### ISSUE TITLE
Stale cache breaks aws credentials refresh

### ISSUE THREAD

**Issue by mshavliuk** [langchain-ai/langsmith-sdk#1507]
When langsmith requests caching is turned on, it also caches AWS credential requests to `https://portal.sso.eu-west-1.amazonaws.com/federation/credentials` so boto3 can no longer obtain the updated session token, which leads to the following error:

```
Failed to retrieve token: Credentials were refreshed, but the refreshed credentials are still expired.
```

More specifically, the [`refresh_using`](https://github.com/boto/botocore/blob/d7df9ed09046c0e3975a440e651013bcaacc70e5/botocore/credentials.py#L538) method of botocore receives cached outdated value which then leads to credentials validation error.

## To reproduce
1. In my specific setup I use AWS SSO session, set up by running `aws configure sso`
2. Set `LANGSMITH_TEST_CACHE=.cache` environment variable
3. Run the following code:
    ```python
    from langchain_aws import ChatBedrockConverse, ChatBedrock
    from langchain_core.prompts import ChatPromptTemplate
    from langsmith import Client
    from langsmith.evaluation import LangChainStringEvaluator
    
    
    def simple(inputs: dict) -> dict:
        llm = ChatBedrockConverse(
            region_name="us-east-1",
            credentials_profile_name="AWS-SSO",
            model_id="amazon.nova-micro-v1:0",
        )
        response = llm.invoke("hello, how are you")
        return {"response": response.content}
    
    
    def run_experiment():
        langsmith_client = Client()
        llm = ChatBedrockConverse(
            region_name="us-east-1",
            credentials_profile_name="AWS-SSO",
            model_id="amazon.nova-micro-v1:0",
        )
    
        conciseness_evaluator = LangChainStringEvaluator(
            "score_string",
            config={"criteria": 'conciseness', "normalize_by": 10, "llm": llm}
        )
    
        experiment_results = langsmith_client.evaluate(
            simple,
            data="small-sample",
            evaluators=[ conciseness_evaluator ],
            upload_results=False,
        )
    
    run_experiment()
    ```
  
## The issue
After executing the script, a new file will be added to the `.cache` directory, where the first entry will look as following: 
```yaml
- request:
    body: null
    headers: {}
    method: GET
    uri: https://portal.sso.eu-west-1.amazonaws.com/federation/credentials?role_name=**stripped**&account_id=**stripped**
  response:
    body:
      string: '{"roleCredentials":{"accessKeyId":"**stripped**","secretAccessKey":"**stripped**","sessionToken":"**stripped**","expiration":1739451266000}}'
    headers:
      Access-Control-Expose-Headers:
      - RequestId
      - x-amzn-RequestId
      Cache-Control:
      - no-cache
      Connection:
      - keep-alive
      Content-Length:
      - '1084'
      Content-Type:
      - application/json
      Date:
      - Thu, 13 Feb 2025 11:54:27 GMT
      RequestId:
      - **stripped**
      Server:
      - AWS SSO
      x-amzn-RequestId:
      - **stripped**
    status:
      code: 200
      message: OK
```

Later on this will lead to the error, described above, caused by stale cache.

## Solution
- allow to specify requests to ignore caching (e.i. `LANGSMITH_TEST_CACHE_IGNORE_HOSTS='https://portal.sso.eu-west-1.amazonaws.com/federation/credentials'`)
-
