### ISSUE TITLE
Token information is not captured after upgrading 

### ISSUE THREAD

**Issue by AlpeshJo** [langchain-ai/langsmith-sdk#197]
Recently we have upgraded LangSmith to 0.0.33 (latest version) from 0.0.12, and we are no longer able to see the token information while "Logging Traces with LangChain", to test post upgrade I am following the standard sample . We tried downgrading LangSmith  to 0.0.28 and 0.0.27  but still facing the issue. 

```
from langchain.chat_models import ChatOpenAI

llm = ChatOpenAI()
llm.predict("Hello, world!")
```

![image](https://github.com/langchain-ai/langsmith-sdk/assets/116248792/44dfcfe7-c065-4280-9682-c542b6720ffe)

Please let me know if this new issue or know issue with solution.

**Comment by hinthornw** [comment]
Hi @AlpeshJo thank you for raising! Sorry to hear some functionality isn't working for you. Could you please confirm the following:
- Is this against the hosted (https://api.smith.langchain.dev) endpoint? 
- Are the tokens still not visible? (some of the information is populated asynchronously so may have backfilled later on)
- Could you confirm your langchain and langsmith version? ( you can run `langsmith env` to see this)

If you are able to share a link to the run, we can help debug it further

**Comment by hinthornw** [comment]
And to confirm, you're running with the rq worker? 

```
angchain-queue:
    image: langchain/${_LANGSMITH_IMAGE_PREFIX-}langchainplus-backend:latest
    environment:
      - LANGCHAIN_ENV=local_docker
      - LOG_LEVEL=warning
    entrypoint: "rq worker --with-scheduler -u redis://langchain-redis:6379 --serializer lc_database.queue.serializer.ORJSONSerializer --worker-class lc_database.queue.worker.Worker --connection-class lc_database.queue.connection.RedisRetry"
    ```
